Fix: ExternalScript Plugins (v1) not exporting.
ExternalScript style plugins (v1) didn't report their page_section.

This was causing page export/import and copy to fail as in the following stack trace:

```
A NoMethodError occurred in sequences#export:
  undefined method `page_section' for #<Embeddable::ExternalScript:0x00000008483c00>

```